title: La MonaTyping
author: Viviana Romero Alarcon
Description: Following the ups and downs of my learning process
url: "https://alarconvv.github.io"
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
color:
  header: "#000"
  gradient_left: "#06252e"
  gradient_right: "#07b4ba"
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/VivianaRomeroAlarcon.pdf"
  - title: "Contact"
    url: "/contact.md"

    social_links:
  - title: "Twitter"
    url: "https://twitter.com/alarconvv"
    icon: "fab fa-twitter"
  - title: "Facebook"
    url: "https://www.github.com/alarconvv"
    icon: "fab fa-github"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/alarconvv"
    icon: "fab fa-linkedin-in"
