name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Replace with your Ruby version
        architecture: arm64
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake test
